baseURL: "https://tharuka-jay.netlify.app"
languageCode: "en-us"
title: "Tharuka Jay"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Tharuka Jayawardane"
  description: My portfolio
  favicon: "/spinner.png"

  useBootstrapCDN: false
  mathjax: false
  animate: true

  theme:
    defaultTheme: "dark"

  font:
    fontSize: 1rem  
    fontWeight: 400 
    lineHeight: 1.5 
    textAlign: left 

  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/spinner.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: true
    brandName: "Tharuka Jayawardane"
    disableSearch: true
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello.. I'm"
    title: "Tharuka"
    subtitle: "I am a developer"
    content: "I like to work on personal projects and learn new things along the way"
    image: /images/hero.jpg
    bottomImage:
      enable: true
    roundImage: true
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/privateDuck
      customIcons:
        - icon: /stovf.png
          url: "https://stackoverflow.com/users/16094602/privateduck"
        - icon: /linkedin.png
          url: "https://www.linkedin.com/in/tharuka-jayawardane-in/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/oogway.png"
    content: |-
      I'm a dedicated software developer with a passion for developing simulation software and games. Currently pursuing a bachelor's degree in computer science, my background spans computer science, physics, and mathematics.

      I excel at problem solving and always like to take on new challenges.
    skills:
      enable: true
      title: "Here are a few languages and tools I'm familiar with:"
      items:
        - "C++"
        - "C#"
        - "Java"
        - "Python"
        - "Unity"
        - "Blender"

  # Experience
  experience:
    enable: false

  # Education
  education:
    enable: true
    index: false
    items:
      - title: "Bachelor of Science (Honours) in Computer Science"
        school:
          name: "University of Kelaniya, Sri Lanka"
          url: "https://www.kln.ac.lk/"
        date: "Sep 2023 - present"
        GPA: ""
        content: |-
          Extracurricular Activities
            - Member of the AIESEC Club of Kelaniya University
        featuredLink:
          enable: false
          url: /images/hero.jpg
      - title: "School"
        school:
          name: "Ananda College"
          url: "https://www.anandacollege.edu.lk/"
        date: "2007 - 2020"
        featuredLink:
          enable: false

  # Achievements
  achievements:
    enable: false

  # projects
  projects:
    enable: true
    items:
      - title: PhysiX 2D
        content: An advanced yet easy to use physics simulator intended for physics undergrads.
        image: /images/projects/physx.jpg
        featured:
          name: Still in prototype phase
          link: https://tharuka-jay.netlify.app
        badges:
          - "C++"
          - "Direct 3D"
        links:
          - icon: fab fa-github
            url: https://github.com/privateDuck

      - title: LogicFlow
        content: A GUI application for evaluating boolean and logical expression and simulating digital circuits
        image: /images/projects/noimg.jpg
        featured:
          name: Currently in development
          link: https://github.com/privateDuck
        badges:
          - "C++"
          - "ImGui"
        links:
          - icon: fab fa-github
            url: https://github.com/privateDuck

      - title: G2D FFT
        content: A Unity Based GPU-Accelerated Radix-2 2D-FFT Library
        image: /images/projects/fft.jpg
        featured:
          name: Project
          link: https://github.com/privateDuck/G2D-FFT
        badges:
          - "C#"
          - "Unity"
        links:
          - icon: fab fa-github
            url: https://github.com/privateDuck/G2D-FFT

      - title: ColorLite
        content: A simple .NET library for working with common color spaces
        image: /images/projects/noimg.jpg
        featured:
          name: Project
          link: https://github.com/privateDuck/ColorLite
        badges:
          - "C#"
        links:
          - icon: fab fa-github
            url: https://github.com/privateDuck/ColorLite

      - title: Sygon
        content: A powerful dataset generator and a statistical analyzer
        image: /images/projects/stats.png
        featured:
          name: Currently in development
          link: https://github.com/privateDuck
        badges:
          - "C++"
          - "ImGui"
        links:
          - icon: fab fa-github
            url: https://github.com/privateDuck

  #Contact
  contact:
    enable: true
    content: I'm always available, send me an email anytime
    email: stsp.official@gmail.com
    btnName: Send Email
    formspree:
      enable: true
      formId: xzbnbkkw # https://formspree.io/f/xzbnbkkw'
      emailCaption: "Your email address"
      messageCaption: "Type your messege"

  footer:
    recentPosts:
      path: "blogs"
      count: 0
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/privateDuck
      linkedin: https://www.linkedin.com/in/tharuka-jayawardane-in/

  listPages:
    disableFeaturedImage: true

  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "2006, Jan 2"
    articleList: "2006, Jan 2"
    articleRecent: "2006, Jan 2"

  customScripts:
